// dependencies
import Header from "@/components/layout/Header";
import "./globals.css";

// metadata
export const metadata = {
  title: "Stay Swift Hotel Booking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
